### ISSUE TITLE
Add support for nvim-specific highlight groups such as "Whitespace"

### ISSUE THREAD

**Issue by bool3max** [jeffkreeftmeijer/vim-dim#4]
`neovim` has introduced saner highlight groups for stuff such as characters output by `listchars`. 

An example is `Whitespace`, which declares the style and color used by visible space and newline characters.

**Comment by bool3max** [comment]
It appears that in neovim, `Whitespace` is automatically bound to `NonText`, which `dim` already sets.

**Comment by jeffkreeftmeijer** [comment]
Hey @bool3max, thanks for suggesting this. I’d be open to adding NeoVim-specific highlight groups, given that they aren’t direct aliases for Vim’s default ones.

I haven’t looked into this, but I can imagine these would be a bit more fine-grained than Vim’s.

Please feel free to open a pull request if you find a highlight group we haven’t covered that we can improve on by ANSIfying or dimming the colors.
